baseURL = "https://cjcsoftwaresolutions.co.uk"
languageCode = "en-us"
title = "CJC Software Solutions Ltd."
theme = "LeaveIt"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""

preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[params]
    since = 2018
    author = "Chris Clarkson"                           # Author's name
    avatar = "img/cjcss_logo.jpg"           # Author's avatar
    subtitle = "Cloud and Security Consultancy"         # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other

    google_verification = ""
   
    description = "" # site description
    keywords = "" # site keywords



[params.social]
    GitHub = "CJCSoftwareSolutions"
    Twitter = "ClarksonCJ"
    Email   = "info@cjcsoftwaresolutions.co.uk"
    Linkedin = "cjclarkson"
